name: Build

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use .NET SDK from global.json (fallback 8.x)
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/OpsLite/OpsLite.csproj

      - name: Build (Release)
        run: dotnet build src/OpsLite/OpsLite.csproj --configuration Release --no-restore

      - name: Run unit tests (if present)
        run: |
          if ls **/*Tests.csproj 1> /dev/null 2>&1; then
            dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
          else
            echo "No *Tests.csproj found – skipping tests."
          fi

      - name: Publish (artifact)
        run: dotnet publish src/OpsLite/OpsLite.csproj -c Release -o ./out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpsLite-publish
          path: out
